name: shell commands
on: [push]
jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello anji"
      - name: echo multi line string
        run: |
          node -v
          npm -v
          